### ISSUE TITLE
Publish Library 

### ISSUE THREAD

**Issue by MarkyC** [SysdataSpA/FancyAccordionView#5]
Ciao!

First of all, **this is a fantastic library**, thank you for creating it!

I have a concern with the packaging though. As a user, I have had to download your git repo,   `gradle build fancyaccodionview.aar` and add it to my project like:

```
// project build.gradle
allprojects {
    repositories {
        flatDir {
            dirs 'src/main/libs'
        }
    }
}

// app build.gradle
dependencies {
    compile(name:'fancyaccordionview', ext:'aar')
}
```

But this is tedious. Most libraries choose to distribute their code using something like [JitPack](https://jitpack.io/docs/ANDROID/) so user's can add your library simply by adding:

```
// app build.gradle
dependencies {
    implementation "com.android.support:multidex:1.0.3"
}
```

Are there any plans to publish this library publicly?

**Comment by Ahmad-Ayman** [comment]
+1

**Comment by aguitto** [comment]
published, thank you for your support
