### ISSUE TITLE
Multiple layouts for collapse view and expand view

### ISSUE THREAD

**Issue by xavierskywalker** [SysdataSpA/FancyAccordionView#8]
Hi, I was wondering if there is a way to have multiple layout for collapse view and expand view, like below.
- collapse layout 1 v
   expand layout 1
- collapse layout 2 v
   expand layout 2
- collapse layout 3 v
   expand layout 3

**Comment by Frandall** [comment]
I also want to know about this. for a moment I create new list for each new layout. I consider modifying the factory and adding if statement in the viewholder but hadn't have the time to try to implement that.

**Comment by aguitto** [comment]
Take a look at this branch https://github.com/SysdataSpA/FancyAccordionView/tree/feature/view_types , we will merge it soon and it will allow you to use this library with multiple layout types.
